### PR TITLE
Method to GetEquippedVirtualGood using the category name

### PR DESCRIPTION
**Pull request by prodigga**
Added a method to GetEquippedVirtualGood using the category name, so you
could use

StoreInventory.GetEquippedVirtualGood(YourStoreAssets.YOUR_CATEGORY.name)
to find goods equipped in that category. #479

### CODE REVIEW

**Comment by oneclickdev** [comment]
hey @prodigga, thanks for solution, but you have so many files changed and commits so I decided to make pull request with just one method (and one file updated); 
you may discard that one request if here is nothing except that method...

**Comment by prodigga** [comment]
Sorry I must have messed up, thought my pull request just says one file changed?

**Comment by oneclickdev** [comment]
no. it says many files changed:
https://www.dropbox.com/s/rnyss5wny2mqmlp/Screenshot%202016-07-16%2016.54.06.png?dl=0

and I'm sure it's pretty hard for soomla guys to review it and accept.

also it has conflicts
https://www.dropbox.com/s/lmo6850aojnlon1/Screenshot%202016-07-16%2016.55.04.png?dl=0

don't you see it? or is it something I can't figure out?

**Comment by prodigga** [comment]
Not sure what's happened but this is all I commited:

https://github.com/prodigga/unity3d-store/commit/991296729a8a6d0372ca851c2febc03cc06e7156

Maybe I messed up somewhere. Honesty, no idea. Lol. I do not have much experience with pull request on GitHub sorry!

**Comment by oneclickdev** [comment]
that's not a problem

seems you requests to pull all your changes except only one:
https://www.dropbox.com/s/c6tqsq43nmqm4sd/Screenshot%202016-07-16%2017.36.07.png?dl=0

**Pull request closed without merging**
