### PR TITLE
An Alternative approach to caching

### PR DESCRIPTION
**Pull request by mksbamford**
Cached value is updated immediately then sent to data store
Cached values are stored in Virtual Items
Balance terminology changed to Value as more generic

Resolves this issue:
http://answers.soom.la/t/currency-balance-not-updating/2229

### CODE REVIEW

**Comment by refaelos** [comment]
Thanks @mksbamford !

The idea you have here is good but I'm afraid it might cause some inconsistencies of data between Unity and the native storage. The way it was implemented before really took care of multiple edge cases.

I want to help you solve the original issue. Can we go back to that?

**Comment by mksbamford** [comment]
If we could solve the original issue that would be great, but there are no errors or anything to suggest what's wrong. It just doesn't work.
What edge cases do you see causing issues with this approach?

**Comment by refaelos** [comment]
What do you mean by `the balance changed event isn't firing` ?
If you saw that it's not firing let me know. I didn't see this happening...

I didn't test all your code but one thing I can say for sure is that b/c you deleted all refreshes on the events that "come" from the native side then there might be a change on the native side that is not reflected in "Unity" side. This is a problem.

**Comment by mksbamford** [comment]
So are far as I can tell, the problem I was having was that the unity cache was never being updated to match the native side. This suggests that RefreshOnGoodBalanceChanged is never called, and I could not find any references to it in the Unity code other than in the editor code. So I assume it is meant to be called from native, but for some reason it is not.

Other than initialisation (which I handled), I was not aware the native side could change on its own, when would this happen?

**Comment by refaelos** [comment]
Can you try catching the onBalanceChanged event? If you don't know how you can look here: http://know.soom.la/unity/store/store_events/#OnGoodBalanceChanged

If this event is not thrown (when you actually change the balance), then there's a problem (probably the prefab is not in the scene).

The native side might make changes to the data and you want it to be reflected in Unity. It might happen through plugins or other scenarios.

**Comment by refaelos** [comment]
Can you try catching the onBalanceChanged event? If you don't know how you can look here: http://know.soom.la/unity/store/store_events/#OnGoodBalanceChanged

If this event is not thrown (when you actually change the balance), then there's a problem (probably the prefab is not in the scene).

The native side might make changes to the data and you want it to be reflected in Unity. It might happen through plugins or other scenarios.

**Comment by mksbamford** [comment]
CoreEvents and StoreEvents are both in the scene.

I am refering to the StoreInventory's RefreshOnCurrencyBalanceChanged method, which updates localItemBalances, localUpgrades and localEquippedGoods. RefreshOnCurrencyBalanceChanged is called in the editor code, but not in the device code.
https://github.com/soomla/unity3d-store/blob/master/Soomla/Assets/Plugins/Soomla/Store/StoreInventory.cs

**Comment by refaelos** [comment]
It's supposed to be called on both.

Can you make sure you're getting onCurrencyChanged event? It's all related ...

**Comment by mksbamford** [comment]
So I managed to get some more useful logs:

setting balance 100 to X.
fetching balance for virtual item with itemId: X
trying to fetch a value for key: currency.X.balance
the fetched value is 100
the balance for X is 100
setting 100 for key: currency.X.balance
SendMessage: object StoreEvents not found!

Is the StoreEvents object being searched for my name is native?

**Comment by refaelos** [comment]
Yes. Why? did you change the name?

This is what I was looking for. It's now clear that events are not thrown in Unity. Make sure the Prefabs are added to the scene, otherwise it's impossible to transfer the events.

**Comment by mksbamford** [comment]
As I have multiple scenes, I'm instantiating the prefabs on first load. However, this means that they are named "StoreEvents(Clone)" and "CoreEvents(Clone)".
A simple fix for this would be for the Events components to force the name of their gameobject to the required name. Assuming this works, I will make a new pull request with the changes.

While I have your attention, is there a reason that ResetBalance is absent from StoreInventory?

**Comment by refaelos** [comment]
I don't understand why you try to invent the wheel here .. Prefabs should simply work with multiple scenes as well. Someone asked this question in the SOOMLA forum before. Try to search there.

If you have another question... post it on another issue here or (preferably) on the SOOMLA forum.

**Comment by mksbamford** [comment]
From a scene management perspective it doesn't make sense to duplicate the prefabs in every scene. Especially if you have a lot of scenes.

**Comment by refaelos** [comment]
I didn't say that. Ask on the forum how they do that. Or you can also search on the forum for people who did that before.

**Comment by mksbamford** [comment]
That is how its done before. The StoreEvents and CoreEvents etc components use a unity singleton pattern whereby you place the prefab in all your scenes and all but the first instance is destroyed.

**Comment by refaelos** [comment]
I seriously don't know. Again, you can ask there.

**Pull request closed without merging**
