### PR TITLE
Price getter added to Purchase Types.

### PR DESCRIPTION
**Pull request by NathanielScottStevens**

### CODE REVIEW

**Comment by zentuit** [comment]
Hey this is a good addition. I think it needs a little tweaking for Market purchase types, but I like the idea.

This would eliminate a nice chunk of my UI code.

@refaelos do you want this method?

**Comment by refaelos** [comment]
Yes it might be useful.. but it's possible to get the price pretty easily from the MarketItem.
Can you explain how will this simple getter make your UI code better?

**Comment by refaelos** [comment]
@NathanielScottStevens please merge the latest master to we can merge this PR

**Comment by NathanielScottStevens** [comment]
Sorry, that took so long. For some reason I couldn't merge without losing a couple of the newer changes. Let me know if there are any problems

**Pull request merged**
