### PR TITLE
Weekly PR

### PR DESCRIPTION
**Pull request by EugeneButusov**
+ Improvement #114 Process NULL-pointers in IStoreAssets
 + Docs #165 Remove links to library from unity in github
 + Fix #150 Conflicts with in-app-billing-service-aidl.jar

### CODE REVIEW

**Comment by EugeneButusov** [comment]
@borisspektor @refaelos, it's ready to merge.

**Comment by borisspektor** [comment]
@EugeneButusov where is `Docs #165 Remove links to library from unity in github`?

**Comment by EugeneButusov** [comment]
@borisspektor, there is https://github.com/vedi/unity3d-store/commit/159a688de7ddcdefbcf25db0da8b8fd8f0f5208a

**Comment by borisspektor** [comment]
@EugeneButusov why can't I see it in the `Files changed` tab? o_O

**Comment by EugeneButusov** [comment]
@borisspektor, maybe it's GitHub diff issue. As you remember, we met in the previous release that GitHub shows wrong diff, but all files was here.

**Pull request merged**
